import { SurveyData } from './types'

export const dummySurveys: SurveyData[] = [
  {
    id: '1',
    responden: 'Andi Wijaya',
    bulan: 'January',
    kualitasPengharum: 4,
    pelayananService: 5,
    pelayananComplain: 4,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 5,
    kebersihanAlat: 4,
    ketepatanWaktu: 5,
    kecepatanRespon: 5,
    saran: 'Sangat memuaskan',
    prediksi: 'Sangat Puas',
    probabilitas: 95,
  },
  {
    id: '2',
    responden: 'Budi Santoso',
    bulan: 'January',
    kualitasPengharum: 4,
    pelayananService: 4,
    pelayananComplain: 3,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 4,
    kebersihanAlat: 4,
    ketepatanWaktu: 4,
    kecepatanRespon: 4,
    saran: 'Bagus, terus dipertahankan',
    prediksi: 'Puas',
    probabilitas: 82,
  },
  {
    id: '3',
    responden: 'Citra Dewi',
    bulan: 'February',
    kualitasPengharum: 5,
    pelayananService: 5,
    pelayananComplain: 4,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 5,
    kebersihanAlat: 5,
    ketepatanWaktu: 5,
    kecepatanRespon: 5,
    saran: 'Layanan terbaik',
    prediksi: 'Sangat Puas',
    probabilitas: 98,
  },
  {
    id: '4',
    responden: 'Dian Pratama',
    bulan: 'February',
    kualitasPengharum: 3,
    pelayananService: 3,
    pelayananComplain: 2,
    akanMenggunakan: 'Tidak',
    pelayananDiperpanjang: 'Tidak',
    kualitasAroma: 3,
    kebersihanAlat: 2,
    ketepatanWaktu: 2,
    kecepatanRespon: 2,
    saran: 'Perlu perbaikan kualitas',
    prediksi: 'Tidak Puas',
    probabilitas: 88,
  },
  {
    id: '5',
    responden: 'Eka Putri',
    bulan: 'March',
    kualitasPengharum: 4,
    pelayananService: 4,
    pelayananComplain: 4,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 4,
    kebersihanAlat: 4,
    ketepatanWaktu: 4,
    kecepatanRespon: 3,
    saran: 'Bagus, harap ditingkatkan respon',
    prediksi: 'Puas',
    probabilitas: 79,
  },
  {
    id: '6',
    responden: 'Fajar Hermawan',
    bulan: 'March',
    kualitasPengharum: 5,
    pelayananService: 4,
    pelayananComplain: 5,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 5,
    kebersihanAlat: 4,
    ketepatanWaktu: 5,
    kecepatanRespon: 4,
    saran: 'Layanan bagus, terus dipertahankan',
    prediksi: 'Sangat Puas',
    probabilitas: 91,
  },
  {
    id: '7',
    responden: 'Gita Lestari',
    bulan: 'April',
    kualitasPengharum: 3,
    pelayananService: 4,
    pelayananComplain: 3,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 3,
    kebersihanAlat: 3,
    ketepatanWaktu: 4,
    kecepatanRespon: 3,
    saran: 'Lumayan memuaskan',
    prediksi: 'Puas',
    probabilitas: 75,
  },
  {
    id: '8',
    responden: 'Hendra Kusuma',
    bulan: 'April',
    kualitasPengharum: 4,
    pelayananService: 5,
    pelayananComplain: 4,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 4,
    kebersihanAlat: 5,
    ketepatanWaktu: 5,
    kecepatanRespon: 5,
    saran: 'Profesional dan cepat',
    prediksi: 'Sangat Puas',
    probabilitas: 93,
  },
  {
    id: '9',
    responden: 'Indah Nurjanah',
    bulan: 'May',
    kualitasPengharum: 4,
    pelayananService: 4,
    pelayananComplain: 4,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 4,
    kebersihanAlat: 4,
    ketepatanWaktu: 3,
    kecepatanRespon: 4,
    saran: 'Cukup puas dengan layanannya',
    prediksi: 'Puas',
    probabilitas: 81,
  },
  {
    id: '10',
    responden: 'Joko Supranto',
    bulan: 'May',
    kualitasPengharum: 5,
    pelayananService: 5,
    pelayananComplain: 5,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 5,
    kebersihanAlat: 5,
    ketepatanWaktu: 5,
    kecepatanRespon: 5,
    saran: 'Sempurna, lanjutkan terus',
    prediksi: 'Sangat Puas',
    probabilitas: 99,
  },
  {
    id: '11',
    responden: 'Kirana Shalsa',
    bulan: 'June',
    kualitasPengharum: 3,
    pelayananService: 3,
    pelayananComplain: 3,
    akanMenggunakan: 'Tidak',
    pelayananDiperpanjang: 'Tidak',
    kualitasAroma: 2,
    kebersihanAlat: 3,
    ketepatanWaktu: 3,
    kecepatanRespon: 2,
    saran: 'Kurang memuaskan',
    prediksi: 'Tidak Puas',
    probabilitas: 85,
  },
  {
    id: '12',
    responden: 'Luthfi Ramadan',
    bulan: 'June',
    kualitasPengharum: 4,
    pelayananService: 4,
    pelayananComplain: 4,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 4,
    kebersihanAlat: 4,
    ketepatanWaktu: 4,
    kecepatanRespon: 4,
    saran: 'Memuaskan',
    prediksi: 'Puas',
    probabilitas: 80,
  },
  {
    id: '13',
    responden: 'Mita Ayu',
    bulan: 'July',
    kualitasPengharum: 5,
    pelayananService: 5,
    pelayananComplain: 4,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 5,
    kebersihanAlat: 5,
    ketepatanWaktu: 5,
    kecepatanRespon: 5,
    saran: 'Sangat puas',
    prediksi: 'Sangat Puas',
    probabilitas: 96,
  },
  {
    id: '14',
    responden: 'Nugroho Adi',
    bulan: 'July',
    kualitasPengharum: 4,
    pelayananService: 3,
    pelayananComplain: 3,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 4,
    kebersihanAlat: 3,
    ketepatanWaktu: 3,
    kecepatanRespon: 3,
    saran: 'Lumayan, bisa lebih baik',
    prediksi: 'Puas',
    probabilitas: 72,
  },
  {
    id: '15',
    responden: 'Olivia Wulandari',
    bulan: 'August',
    kualitasPengharum: 4,
    pelayananService: 4,
    pelayananComplain: 4,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 4,
    kebersihanAlat: 4,
    ketepatanWaktu: 4,
    kecepatanRespon: 4,
    saran: 'Bagus',
    prediksi: 'Puas',
    probabilitas: 83,
  },
  {
    id: '16',
    responden: 'Pande Sukarta',
    bulan: 'August',
    kualitasPengharum: 5,
    pelayananService: 5,
    pelayananComplain: 5,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 5,
    kebersihanAlat: 5,
    ketepatanWaktu: 5,
    kecepatanRespon: 5,
    saran: 'Excellent service',
    prediksi: 'Sangat Puas',
    probabilitas: 97,
  },
  {
    id: '17',
    responden: 'Qori Yuanita',
    bulan: 'September',
    kualitasPengharum: 3,
    pelayananService: 4,
    pelayananComplain: 3,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 3,
    kebersihanAlat: 4,
    ketepatanWaktu: 3,
    kecepatanRespon: 3,
    saran: 'Cukup puas',
    prediksi: 'Puas',
    probabilitas: 74,
  },
  {
    id: '18',
    responden: 'Rinto Harahap',
    bulan: 'September',
    kualitasPengharum: 4,
    pelayananService: 4,
    pelayananComplain: 4,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 4,
    kebersihanAlat: 4,
    ketepatanWaktu: 4,
    kecepatanRespon: 4,
    saran: 'Memuaskan',
    prediksi: 'Puas',
    probabilitas: 84,
  },
  {
    id: '19',
    responden: 'Sinta Wijaya',
    bulan: 'October',
    kualitasPengharum: 5,
    pelayananService: 5,
    pelayananComplain: 5,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 5,
    kebersihanAlat: 5,
    ketepatanWaktu: 5,
    kecepatanRespon: 5,
    saran: 'Terbaik',
    prediksi: 'Sangat Puas',
    probabilitas: 94,
  },
  {
    id: '20',
    responden: 'Tommy Irawan',
    bulan: 'October',
    kualitasPengharum: 4,
    pelayananService: 4,
    pelayananComplain: 4,
    akanMenggunakan: 'Ya',
    pelayananDiperpanjang: 'Ya',
    kualitasAroma: 4,
    kebersihanAlat: 4,
    ketepatanWaktu: 4,
    kecepatanRespon: 4,
    saran: 'Puas',
    prediksi: 'Puas',
    probabilitas: 81,
  },
]
